name: CI/CD Pipeline for Spring Boot QA Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build, run unit tests, and package JAR
        run: mvn clean package -Dtest=QaApplicationTests
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb

      - name: List target directory for debug
        run: ls -la target/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/QA-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target/

      - name: Display build success
        run: |
          echo "🎉 CI/CD Pipeline Completed Successfully!"
          echo "✅ Build + Unit Tests Passed"
          echo "📦 JAR ready for deployment!"
