name: CI/CD Pipeline for Spring Boot QA Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and run unit tests
        run: mvn clean package
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar

  selenium-tests:
    needs: build-and-test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target/

      - name: Start Spring Boot application
        run: |
          java -jar target/*.jar --server.port=8080 &
          echo $! > spring-boot-app.pid
          npm install -g wait-on
          wait-on http://localhost:8080/actuator/health --timeout 60000
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Start Frontend Development Server
        working-directory: ./frontend
        run: |
          nohup npm start > server.log 2>&1 &
          echo $! > frontend.pid
          npm install -g wait-on
          wait-on http://localhost:3000 --timeout 120000

      - name: Install Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xvfb
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y

      - name: Run Selenium tests
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x16 &
          mvn test -Dtest=AuthenticationSeleniumTests -Dselenium.headless=true
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb

      - name: Stop servers
        run: |
          if [ -f frontend.pid ]; then kill $(cat frontend.pid) 2>/dev/null || true; fi
          if [ -f spring-boot-app.pid ]; then kill $(cat spring-boot-app.pid) 2>/dev/null || true; fi
      # Optional: Print frontend logs if something goes wrong
      - name: Print Frontend Logs on Failure
        if: failure()
        working-directory: ./frontend
        run: cat server.log
  api-tests:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: application-jar
          path: target/

      - name: Start Spring Boot application
        run: |
          java -jar target/*.jar --server.port=8080 &
          echo $! > spring-boot-app.pid
          npm install -g wait-on
          wait-on http://localhost:8080/actuator/health
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb

      - name: Install Newman for API tests
        run: npm install -g newman

      - name: Run API tests
        run: |
          newman run postman-collection.json || true
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb

      - name: Stop Spring Boot application
        run: |
          if [ -f spring-boot-app.pid ]; then
            kill $(cat spring-boot-app.pid) || true
            rm spring-boot-app.pid
          fi

  deploy:
    needs: [build-and-test, selenium-tests, api-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built JAR
        uses: actions/download-artifact@v3
        with:
          name: application-jar
          path: target/

      - name: Display build success
        run: |
          echo "🎉 CI/CD Pipeline Completed Successfully!"
          echo "✅ Build + Unit Tests Passed"
          echo "✅ Selenium Tests Passed"
          echo "✅ API Tests Passed"
          echo "📦 JAR ready for deployment!"
